name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: 'The name of the deployable artifact to files'
                required: false
                type: string
                default: dist-files
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/download-artifact@v3
              with:
                name: ${{ inputs.artifact-name }}
            - name: List files
              run: ls
            - name: Output information
              run: echo "Deploying to ${{ github.ref }}"